### ISSUE TITLE
跑不起来

### ISSUE THREAD

**Issue by jianmu123** [miqilin21/myBlog#10]
安装readme文件来安装依赖和启动服务，但是跑不起来

**Comment by miqilin21** [comment]
是有报错吗？截图发我看看

**Comment by zonemeen** [comment]
> 安装readme文件来安装依赖和启动服务，但是跑不起来

是有报错吗？截图发我看看

**Comment by jianmu123** [comment]
> > 安装readme文件来安装依赖和启动服务，但是跑不起来
> 
> 是有报错吗？截图发我看看
![admin](https://user-images.githubusercontent.com/68387690/108579914-2800d880-7364-11eb-9003-89b1fa6d969d.png)
![web](https://user-images.githubusercontent.com/68387690/108579919-2b945f80-7364-11eb-894d-a6ea7efc0578.png)

**Comment by ransihao** [comment]
我也是这个报错怎么解决的

**Comment by zerotower69** [comment]
@ransihao 你可以了吗，是少了一个包，"@babel/compat-data": "7.9.0" 这个，把它装了就大功告成了

**Comment by jianmu123** [comment]
不行啊，admin的还是跑不起来

**Comment by jianmu123** [comment]
@zerotower69

**Comment by jianmu123** [comment]
@zerotower69  不行啊，admin的还是跑不起来

**Comment by zerotower69** [comment]
@jianmu123 邮箱多少，一下我把测试没问题的代码压缩发给你。

**Comment by jianmu123** [comment]
@zerotower69  1336108285@qq.com

**Comment by workinggirlkill** [comment]
跑起来了没有数据，啥原因，切后台我不知道密码和账号

**Comment by workinggirlkill** [comment]
怎么调用数据库的东西

**Comment by zyqbiubiu** [comment]
你好 我跑起来了 但是修改了一些东西之后页面上没有变化 不知道是为什么。
