### ISSUE TITLE
iBlog\admin\src\views\UserList.vue   121:37  error  'res' is defined but never used  no-unused-vars

### ISSUE THREAD

**Issue by PureWaterSun** [miqilin21/myBlog#14]
登录后台就报这个错误

![微信截图_20220913170535](https://user-images.githubusercontent.com/42731510/189860580-5cbc1e89-eb6c-4ea2-b3c9-564f5e0200d8.png)

**Comment by ghost** [comment]
> 登录后台就报这个错误
> 
> ![微信截图_20220913170535](https://user-images.githubusercontent.com/42731510/189860580-5cbc1e89-eb6c-4ea2-b3c9-564f5e0200d8.png)

去UserList.vue文件中把没有用到res删掉就好了

**Comment by PureWaterSun** [comment]
这是来自QQ邮箱的自动回复邮件。
 已收到！
