### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by jessy-x** [miqilin21/myBlog#3]
有数据库的数据吗？学习中

**Comment by miqilin21** [comment]
> 有数据库的数据吗？学习中

你好，你想学数据库还是什么？

**Comment by miqilin21** [comment]
你好，请问你是想学习数据库还是什么？

**Comment by zonemeen** [comment]
你好，请问你是想学习数据库还是项目什么的吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jessy-x"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月23日(星期六) 下午2:36
收件人:&nbsp;"miqilin21/myBlog"<myBlog@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[miqilin21/myBlog] 你好 (#3)





 
有数据库的数据吗？学习中

**Comment by jessy-x** [comment]
你好，学生学习中，想要下博客数据库中的数据，后台不知道怎么登录，了解到是加密形式，没办法直接添加，只是当学习用，请你放心



---原始邮件---
发件人: "米淇淋"<notifications@github.com&gt;
发送时间: 2020年5月23日(周六) 下午2:48
收件人: "miqilin21/myBlog"<myBlog@noreply.github.com&gt;;
抄送: "jessy-x"<1101130160@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [miqilin21/myBlog] 你好 (#3)




 你好，请问你是想学习数据库还是项目什么的吗？ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"jessy-x"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年5月23日(星期六) 下午2:36 
 收件人:&amp;nbsp;"miqilin21/myBlog"<myBlog@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;[miqilin21/myBlog] 你好 (#3) 
 
 
 
 
 
   
 有数据库的数据吗？学习中

**Comment by zonemeen** [comment]
后台是可以注册的，然后就可以直接登录了，你是学生的话应该蛮多时间的，如果你想学类似的架构的话，自己琢磨还是蛮慢的，我推荐你去看一个B站的教程，很清晰，我这个博客也是参考那个教程架构的，里面讲的数据库知识也是mongodb，教程地址：https://www.bilibili.com/video/av51931842&nbsp; &nbsp;你如果把这个做王者荣耀手机官网全部做下来，好好琢磨还是蛮不错的项目，也可以自己后期改动成属于自己的项目，以后你毕业找工作就可以把这些项目放简历里了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jessy-x"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月23日(星期六) 下午2:55
收件人:&nbsp;"miqilin21/myBlog"<myBlog@noreply.github.com&gt;;
抄送:&nbsp;"米淇淋"<994718917@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [miqilin21/myBlog] 你好 (#3)





 你好，学生学习中，想要下博客数据库中的数据，后台不知道怎么登录，了解到是加密形式，没办法直接添加，只是当学习用，请你放心 
 
 
 
 ---原始邮件--- 
 发件人: "米淇淋"<notifications@github.com&amp;gt; 
 发送时间: 2020年5月23日(周六) 下午2:48 
 收件人: "miqilin21/myBlog"<myBlog@noreply.github.com&amp;gt;; 
 抄送: "jessy-x"<1101130160@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题: Re: [miqilin21/myBlog] 你好 (#3) 
 
 
 
 
  你好，请问你是想学习数据库还是项目什么的吗？  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;"jessy-x"<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年5月23日(星期六) 下午2:36  
  收件人:&amp;amp;nbsp;"miqilin21/myBlog"<myBlog@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;[miqilin21/myBlog] 你好 (#3)  
   
   
   
   
   
     
  有数据库的数据吗？学习中

**Comment by jessy-x** [comment]
好的，谢谢你的建议，我去看下



---原始邮件---
发件人: "米淇淋"<notifications@github.com&gt;
发送时间: 2020年5月23日(周六) 下午3:02
收件人: "miqilin21/myBlog"<myBlog@noreply.github.com&gt;;
抄送: "jessy-x"<1101130160@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [miqilin21/myBlog] 你好 (#3)




 后台是可以注册的，然后就可以直接登录了，你是学生的话应该蛮多时间的，如果你想学类似的架构的话，自己琢磨还是蛮慢的，我推荐你去看一个B站的教程，很清晰，我这个博客也是参考那个教程架构的，里面讲的数据库知识也是mongodb，教程地址：https://www.bilibili.com/video/av51931842&amp;nbsp; &amp;nbsp;你如果把这个做王者荣耀手机官网全部做下来，好好琢磨还是蛮不错的项目，也可以自己后期改动成属于自己的项目，以后你毕业找工作就可以把这些项目放简历里了 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"jessy-x"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年5月23日(星期六) 下午2:55 
 收件人:&amp;nbsp;"miqilin21/myBlog"<myBlog@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"米淇淋"<994718917@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [miqilin21/myBlog] 你好 (#3) 
 
 
 
 
 
  你好，学生学习中，想要下博客数据库中的数据，后台不知道怎么登录，了解到是加密形式，没办法直接添加，只是当学习用，请你放心  
   
   
   
  ---原始邮件---  
  发件人: "米淇淋"<notifications@github.com&amp;amp;gt;  
  发送时间: 2020年5月23日(周六) 下午2:48  
  收件人: "miqilin21/myBlog"<myBlog@noreply.github.com&amp;amp;gt;;  
  抄送: "jessy-x"<1101130160@qq.com&amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;gt;;  
  主题: Re: [miqilin21/myBlog] 你好 (#3)  
   
   
   
   
   你好，请问你是想学习数据库还是项目什么的吗？   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:&amp;amp;amp;nbsp;"jessy-x"<notifications@github.com&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2020年5月23日(星期六) 下午2:36   
   收件人:&amp;amp;amp;nbsp;"miqilin21/myBlog"<myBlog@noreply.github.com&amp;amp;amp;gt;;   
   抄送:&amp;amp;amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;[miqilin21/myBlog] 你好 (#3)   
     
     
     
     
     
       
   有数据库的数据吗？学习中

**Comment by zonemeen** [comment]
不客气哒，那我把issue关咯，刚刚发的那个地址有空格符了，重发一遍，https://www.bilibili.com/video/av51931842




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jessy-x"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月23日(星期六) 下午3:07
收件人:&nbsp;"miqilin21/myBlog"<myBlog@noreply.github.com&gt;;
抄送:&nbsp;"米淇淋"<994718917@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [miqilin21/myBlog] 你好 (#3)





 好的，谢谢你的建议，我去看下 
 
 
 
 ---原始邮件--- 
 发件人: "米淇淋"<notifications@github.com&amp;gt; 
 发送时间: 2020年5月23日(周六) 下午3:02 
 收件人: "miqilin21/myBlog"<myBlog@noreply.github.com&amp;gt;; 
 抄送: "jessy-x"<1101130160@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题: Re: [miqilin21/myBlog] 你好 (#3) 
 
 
 
 
  后台是可以注册的，然后就可以直接登录了，你是学生的话应该蛮多时间的，如果你想学类似的架构的话，自己琢磨还是蛮慢的，我推荐你去看一个B站的教程，很清晰，我这个博客也是参考那个教程架构的，里面讲的数据库知识也是mongodb，教程地址：https://www.bilibili.com/video/av51931842&amp;amp;nbsp; &amp;amp;nbsp;你如果把这个做王者荣耀手机官网全部做下来，好好琢磨还是蛮不错的项目，也可以自己后期改动成属于自己的项目，以后你毕业找工作就可以把这些项目放简历里了  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;"jessy-x"<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年5月23日(星期六) 下午2:55  
  收件人:&amp;amp;nbsp;"miqilin21/myBlog"<myBlog@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"米淇淋"<994718917@qq.com&amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [miqilin21/myBlog] 你好 (#3)  
   
   
   
   
   
   你好，学生学习中，想要下博客数据库中的数据，后台不知道怎么登录，了解到是加密形式，没办法直接添加，只是当学习用，请你放心   
     
     
     
   ---原始邮件---   
   发件人: "米淇淋"<notifications@github.com&amp;amp;amp;gt;   
   发送时间: 2020年5月23日(周六) 下午2:48   
   收件人: "miqilin21/myBlog"<myBlog@noreply.github.com&amp;amp;amp;gt;;   
   抄送: "jessy-x"<1101130160@qq.com&amp;amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;amp;gt;;   
   主题: Re: [miqilin21/myBlog] 你好 (#3)   
     
     
     
     
    你好，请问你是想学习数据库还是项目什么的吗？    
       
       
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人:&amp;amp;amp;amp;nbsp;"jessy-x"<notifications@github.com&amp;amp;amp;amp;gt;;    
    发送时间:&amp;amp;amp;amp;nbsp;2020年5月23日(星期六) 下午2:36    
    收件人:&amp;amp;amp;amp;nbsp;"miqilin21/myBlog"<myBlog@noreply.github.com&amp;amp;amp;amp;gt;;    
    抄送:&amp;amp;amp;amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;amp;amp;amp;gt;;    
    主题:&amp;amp;amp;amp;nbsp;[miqilin21/myBlog] 你好 (#3)    
       
       
       
       
       
         
    有数据库的数据吗？学习中

**Comment by jessy-x** [comment]
嗯嗯，好的，谢啦



---原始邮件---
发件人: "米淇淋"<notifications@github.com&gt;
发送时间: 2020年5月23日(周六) 下午3:10
收件人: "miqilin21/myBlog"<myBlog@noreply.github.com&gt;;
抄送: "jessy-x"<1101130160@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [miqilin21/myBlog] 你好 (#3)




 不客气哒，那我把issue关咯，刚刚发的那个地址有空格符了，重发一遍，https://www.bilibili.com/video/av51931842 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"jessy-x"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年5月23日(星期六) 下午3:07 
 收件人:&amp;nbsp;"miqilin21/myBlog"<myBlog@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"米淇淋"<994718917@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [miqilin21/myBlog] 你好 (#3) 
 
 
 
 
 
  好的，谢谢你的建议，我去看下  
   
   
   
  ---原始邮件---  
  发件人: "米淇淋"<notifications@github.com&amp;amp;gt;  
  发送时间: 2020年5月23日(周六) 下午3:02  
  收件人: "miqilin21/myBlog"<myBlog@noreply.github.com&amp;amp;gt;;  
  抄送: "jessy-x"<1101130160@qq.com&amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;gt;;  
  主题: Re: [miqilin21/myBlog] 你好 (#3)  
   
   
   
   
   后台是可以注册的，然后就可以直接登录了，你是学生的话应该蛮多时间的，如果你想学类似的架构的话，自己琢磨还是蛮慢的，我推荐你去看一个B站的教程，很清晰，我这个博客也是参考那个教程架构的，里面讲的数据库知识也是mongodb，教程地址：https://www.bilibili.com/video/av51931842&amp;amp;amp;nbsp; &amp;amp;amp;nbsp;你如果把这个做王者荣耀手机官网全部做下来，好好琢磨还是蛮不错的项目，也可以自己后期改动成属于自己的项目，以后你毕业找工作就可以把这些项目放简历里了   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:&amp;amp;amp;nbsp;"jessy-x"<notifications@github.com&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2020年5月23日(星期六) 下午2:55   
   收件人:&amp;amp;amp;nbsp;"miqilin21/myBlog"<myBlog@noreply.github.com&amp;amp;amp;gt;;   
   抄送:&amp;amp;amp;nbsp;"米淇淋"<994718917@qq.com&amp;amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [miqilin21/myBlog] 你好 (#3)   
     
     
     
     
     
    你好，学生学习中，想要下博客数据库中的数据，后台不知道怎么登录，了解到是加密形式，没办法直接添加，只是当学习用，请你放心    
       
       
       
    ---原始邮件---    
    发件人: "米淇淋"<notifications@github.com&amp;amp;amp;amp;gt;    
    发送时间: 2020年5月23日(周六) 下午2:48    
    收件人: "miqilin21/myBlog"<myBlog@noreply.github.com&amp;amp;amp;amp;gt;;    
    抄送: "jessy-x"<1101130160@qq.com&amp;amp;amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;amp;amp;gt;;    
    主题: Re: [miqilin21/myBlog] 你好 (#3)    
       
       
       
       
     你好，请问你是想学习数据库还是项目什么的吗？     
         
         
         
         
     ------------------&amp;amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;amp;nbsp;------------------     
     发件人:&amp;amp;amp;amp;amp;nbsp;"jessy-x"<notifications@github.com&amp;amp;amp;amp;amp;gt;;     
     发送时间:&amp;amp;amp;amp;amp;nbsp;2020年5月23日(星期六) 下午2:36     
     收件人:&amp;amp;amp;amp;amp;nbsp;"miqilin21/myBlog"<myBlog@noreply.github.com&amp;amp;amp;amp;amp;gt;;     
     抄送:&amp;amp;amp;amp;amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;amp;amp;amp;amp;gt;;     
     主题:&amp;amp;amp;amp;amp;nbsp;[miqilin21/myBlog] 你好 (#3)     
         
         
         
         
         
           
     有数据库的数据吗？学习中

**Comment by zonemeen** [comment]
方便的话帮我在博客里留个言啥的，什么都行，谢谢哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jessy-x"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月23日(星期六) 下午3:11
收件人:&nbsp;"miqilin21/myBlog"<myBlog@noreply.github.com&gt;;
抄送:&nbsp;"米淇淋"<994718917@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [miqilin21/myBlog] 你好 (#3)





 嗯嗯，好的，谢啦 
 
 
 
 ---原始邮件--- 
 发件人: "米淇淋"<notifications@github.com&amp;gt; 
 发送时间: 2020年5月23日(周六) 下午3:10 
 收件人: "miqilin21/myBlog"<myBlog@noreply.github.com&amp;gt;; 
 抄送: "jessy-x"<1101130160@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题: Re: [miqilin21/myBlog] 你好 (#3) 
 
 
 
 
  不客气哒，那我把issue关咯，刚刚发的那个地址有空格符了，重发一遍，https://www.bilibili.com/video/av51931842  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;"jessy-x"<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年5月23日(星期六) 下午3:07  
  收件人:&amp;amp;nbsp;"miqilin21/myBlog"<myBlog@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"米淇淋"<994718917@qq.com&amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [miqilin21/myBlog] 你好 (#3)  
   
   
   
   
   
   好的，谢谢你的建议，我去看下   
     
     
     
   ---原始邮件---   
   发件人: "米淇淋"<notifications@github.com&amp;amp;amp;gt;   
   发送时间: 2020年5月23日(周六) 下午3:02   
   收件人: "miqilin21/myBlog"<myBlog@noreply.github.com&amp;amp;amp;gt;;   
   抄送: "jessy-x"<1101130160@qq.com&amp;amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;amp;gt;;   
   主题: Re: [miqilin21/myBlog] 你好 (#3)   
     
     
     
     
    后台是可以注册的，然后就可以直接登录了，你是学生的话应该蛮多时间的，如果你想学类似的架构的话，自己琢磨还是蛮慢的，我推荐你去看一个B站的教程，很清晰，我这个博客也是参考那个教程架构的，里面讲的数据库知识也是mongodb，教程地址：https://www.bilibili.com/video/av51931842&amp;amp;amp;amp;nbsp; &amp;amp;amp;amp;nbsp;你如果把这个做王者荣耀手机官网全部做下来，好好琢磨还是蛮不错的项目，也可以自己后期改动成属于自己的项目，以后你毕业找工作就可以把这些项目放简历里了    
       
       
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人:&amp;amp;amp;amp;nbsp;"jessy-x"<notifications@github.com&amp;amp;amp;amp;gt;;    
    发送时间:&amp;amp;amp;amp;nbsp;2020年5月23日(星期六) 下午2:55    
    收件人:&amp;amp;amp;amp;nbsp;"miqilin21/myBlog"<myBlog@noreply.github.com&amp;amp;amp;amp;gt;;    
    抄送:&amp;amp;amp;amp;nbsp;"米淇淋"<994718917@qq.com&amp;amp;amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;amp;amp;gt;;    
    主题:&amp;amp;amp;amp;nbsp;Re: [miqilin21/myBlog] 你好 (#3)    
       
       
       
       
       
     你好，学生学习中，想要下博客数据库中的数据，后台不知道怎么登录，了解到是加密形式，没办法直接添加，只是当学习用，请你放心     
         
         
         
     ---原始邮件---     
     发件人: "米淇淋"<notifications@github.com&amp;amp;amp;amp;amp;gt;     
     发送时间: 2020年5月23日(周六) 下午2:48     
     收件人: "miqilin21/myBlog"<myBlog@noreply.github.com&amp;amp;amp;amp;amp;gt;;     
     抄送: "jessy-x"<1101130160@qq.com&amp;amp;amp;amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;amp;amp;amp;gt;;     
     主题: Re: [miqilin21/myBlog] 你好 (#3)     
         
         
         
         
      你好，请问你是想学习数据库还是项目什么的吗？      
           
           
           
           
      ------------------&amp;amp;amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;amp;amp;nbsp;------------------      
      发件人:&amp;amp;amp;amp;amp;amp;nbsp;"jessy-x"<notifications@github.com&amp;amp;amp;amp;amp;amp;gt;;      
      发送时间:&amp;amp;amp;amp;amp;amp;nbsp;2020年5月23日(星期六) 下午2:36      
      收件人:&amp;amp;amp;amp;amp;amp;nbsp;"miqilin21/myBlog"<myBlog@noreply.github.com&amp;amp;amp;amp;amp;amp;gt;;      
      抄送:&amp;amp;amp;amp;amp;amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;amp;amp;amp;amp;amp;gt;;      
      主题:&amp;amp;amp;amp;amp;amp;nbsp;[miqilin21/myBlog] 你好 (#3)      
           
           
           
           
           
             
      有数据库的数据吗？学习中

**Comment by zonemeen** [comment]
填你的昵称和QQ邮箱啥的就行了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jessy-x"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月23日(星期六) 下午3:11
收件人:&nbsp;"miqilin21/myBlog"<myBlog@noreply.github.com&gt;;
抄送:&nbsp;"米淇淋"<994718917@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [miqilin21/myBlog] 你好 (#3)





 嗯嗯，好的，谢啦 
 
 
 
 ---原始邮件--- 
 发件人: "米淇淋"<notifications@github.com&amp;gt; 
 发送时间: 2020年5月23日(周六) 下午3:10 
 收件人: "miqilin21/myBlog"<myBlog@noreply.github.com&amp;gt;; 
 抄送: "jessy-x"<1101130160@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题: Re: [miqilin21/myBlog] 你好 (#3) 
 
 
 
 
  不客气哒，那我把issue关咯，刚刚发的那个地址有空格符了，重发一遍，https://www.bilibili.com/video/av51931842  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;"jessy-x"<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年5月23日(星期六) 下午3:07  
  收件人:&amp;amp;nbsp;"miqilin21/myBlog"<myBlog@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"米淇淋"<994718917@qq.com&amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [miqilin21/myBlog] 你好 (#3)  
   
   
   
   
   
   好的，谢谢你的建议，我去看下   
     
     
     
   ---原始邮件---   
   发件人: "米淇淋"<notifications@github.com&amp;amp;amp;gt;   
   发送时间: 2020年5月23日(周六) 下午3:02   
   收件人: "miqilin21/myBlog"<myBlog@noreply.github.com&amp;amp;amp;gt;;   
   抄送: "jessy-x"<1101130160@qq.com&amp;amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;amp;gt;;   
   主题: Re: [miqilin21/myBlog] 你好 (#3)   
     
     
     
     
    后台是可以注册的，然后就可以直接登录了，你是学生的话应该蛮多时间的，如果你想学类似的架构的话，自己琢磨还是蛮慢的，我推荐你去看一个B站的教程，很清晰，我这个博客也是参考那个教程架构的，里面讲的数据库知识也是mongodb，教程地址：https://www.bilibili.com/video/av51931842&amp;amp;amp;amp;nbsp; &amp;amp;amp;amp;nbsp;你如果把这个做王者荣耀手机官网全部做下来，好好琢磨还是蛮不错的项目，也可以自己后期改动成属于自己的项目，以后你毕业找工作就可以把这些项目放简历里了    
       
       
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人:&amp;amp;amp;amp;nbsp;"jessy-x"<notifications@github.com&amp;amp;amp;amp;gt;;    
    发送时间:&amp;amp;amp;amp;nbsp;2020年5月23日(星期六) 下午2:55    
    收件人:&amp;amp;amp;amp;nbsp;"miqilin21/myBlog"<myBlog@noreply.github.com&amp;amp;amp;amp;gt;;    
    抄送:&amp;amp;amp;amp;nbsp;"米淇淋"<994718917@qq.com&amp;amp;amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;amp;amp;gt;;    
    主题:&amp;amp;amp;amp;nbsp;Re: [miqilin21/myBlog] 你好 (#3)    
       
       
       
       
       
     你好，学生学习中，想要下博客数据库中的数据，后台不知道怎么登录，了解到是加密形式，没办法直接添加，只是当学习用，请你放心     
         
         
         
     ---原始邮件---     
     发件人: "米淇淋"<notifications@github.com&amp;amp;amp;amp;amp;gt;     
     发送时间: 2020年5月23日(周六) 下午2:48     
     收件人: "miqilin21/myBlog"<myBlog@noreply.github.com&amp;amp;amp;amp;amp;gt;;     
     抄送: "jessy-x"<1101130160@qq.com&amp;amp;amp;amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;amp;amp;amp;gt;;     
     主题: Re: [miqilin21/myBlog] 你好 (#3)     
         
         
         
         
      你好，请问你是想学习数据库还是项目什么的吗？      
           
           
           
           
      ------------------&amp;amp;amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;amp;amp;nbsp;------------------      
      发件人:&amp;amp;amp;amp;amp;amp;nbsp;"jessy-x"<notifications@github.com&amp;amp;amp;amp;amp;amp;gt;;      
      发送时间:&amp;amp;amp;amp;amp;amp;nbsp;2020年5月23日(星期六) 下午2:36      
      收件人:&amp;amp;amp;amp;amp;amp;nbsp;"miqilin21/myBlog"<myBlog@noreply.github.com&amp;amp;amp;amp;amp;amp;gt;;      
      抄送:&amp;amp;amp;amp;amp;amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;amp;amp;amp;amp;amp;gt;;      
      主题:&amp;amp;amp;amp;amp;amp;nbsp;[miqilin21/myBlog] 你好 (#3)      
           
           
           
           
           
             
      有数据库的数据吗？学习中
